require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/Documentation:
  Enabled: false
