require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
Metrics/BlockLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/Documentation:
  Enabled: false
